"""
Auto-generated ALBERTA active-learning calibration.

Generated by AL/estimate_active_learning_weights.py.
Do not modify manually.

RAW_W_* are the canonical OLS coefficients used by
the acquisition score. W_* are diagnostic coefficients
normalized to sum to one.

Calibration uses chronological-window x side-to-move
percentile normalization of raw H and U.
"""

TEMPORAL_WINDOWS = 6

# Canonical standardized OLS coefficients
RAW_W_H = 0.0008853079602478558
RAW_W_U = 0.17684707645418551
RAW_W_HU = -0.0657795482595458

# Sum-normalized coefficients for diagnostics only
W_H = 0.007907865407027525
W_U = 1.5796569566984107
W_HU = -0.5875648221054383
